@extends('layouts.app')

@section('title', 'Home - TugasKu')

@push('styles')
    <link rel="stylesheet" href="{{ asset('css/homePage.css') }}">
@endpush

@section('content')
    <!-- Left Column -->
    <section class="content-left">
        <div class="greeting">
            <h1></h1>
            <p>Semangat kerjain tugasnya ya!</p>
        </div>

        <div class="first-row">
            <!-- Enhanced Streak Card -->
            <div class="card streak-card">
                <div class="streak-content">
                    <div class="streak-title-container">
                        <h3 id="streak-title" class="streak-title">Memuat...</h3>
                    </div>
                    
                    <div class="streak-visual-container">
                        <!-- Glow effect background -->
                        <div id="streak-glow" class="streak-glow"></div>
                        
                        <!-- Sparkles container -->
                        <div id="streak-sparkles" class="streak-sparkles">
                            <!-- Sparkles will be generated by JS -->
                        </div>
                        
                        <!-- Main streak icon -->
                        <img id="streak-icon" 
                            src="{{ asset('img/flame-icon.png') }}" 
                            alt="Streak Icon" 
                            class="streak-icon">
                    </div>
                    
                    <div class="streak-text-container">
                        <h2 id="streak-text" class="streak-main-text">
                            Kamu memiliki 
                            <span id="streak-count" class="streak-count">0</span> 
                            Streaks!
                        </h2>
                    </div>
                    
                    <!-- Loading indicator -->
                    <div id="streak-loading" class="streak-loading">
                        <div class="loading-spinner"></div>
                    </div>
                </div>
            </div>

            <!-- Enhanced Add Task Card -->
            <div class="card task-card">
                <div class="task-form">
                    <h2>Catat Tugas Disini!</h2>
                    
                    <!-- Task Title Input -->
                    <input type="text" 
                        id="task-title"
                        class="task-input" 
                        placeholder="Judul tugas..."
                        maxlength="100">

                    <!-- Time Section -->
                    <div class="task-time">
                        <h3>Waktu</h3>
                        <div class="time-inputs">
                            <input type="datetime-local" 
                                id="start-time" 
                                class="time-input"
                                required>
                            <span class="time-separator">hingga</span>
                            <input type="datetime-local" 
                                id="end-time" 
                                class="time-input disabled"
                                disabled>
                        </div>
                    </div>

                    <!-- Category Section -->
                    <div class="task-category">
                        <h3>Kategori</h3>
                        <div class="category-row">
                            <div class="category-chips" id="category-buttons-container">
                                <!-- Kategori chips akan diinject di sini (max 3) -->
                            </div>
                            <select class="category-select" id="category-select">
                                <option value="">Lainnya...</option>
                                <!-- Kategori sisanya akan diinject di sini -->
                            </select>
                        </div>
                    </div>

                    <!-- Description & Submit -->
                    <div class="notes-button">
                        <input type="text" 
                            id="task-description"
                            class="task-desc-input" 
                            placeholder="Deskripsi tugas..."
                            maxlength="200">
                        <button class="add-category-btn" id="add-category-btn">
                            <div class="btn-content">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
                                    <path d="M5 12h14" />
                                    <path d="M12 5v14" />
                                </svg>
                            </div>
                            <div class="btn-loading" id="btn-loading" style="display: none;">
                                <div class="loading-spinner"></div>
                            </div>
                        </button>
                    </div>
                    
                    <!-- Error Messages (only show on submit) -->
                    <div class="form-errors" id="form-errors" style="display: none;">
                        <div class="error-message" id="error-message"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="second-row">
            <div class="section-header">
                <h2>Kategori Tugas</h2>
            </div>

            <div class="category-cards" id="category-cards-container"></div>

            <div class="timer-panel">
                <div class="timer-controls">
                    <!-- Tombol Play/Pause -->
                    <button class="timer-btn" id="toggle-btn">
                        <!-- Awalnya tampil ikon Play -->
                        <svg id="icon-toggle" xmlns="http://www.w3.org/2000/svg" width="24" height="24" 
                            viewBox="0 0 24 24" fill="none" stroke="currentColor" 
                            stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                            <polygon points="5 3 19 12 5 21 5 3" />
                        </svg>
                    </button>
                
                    <!-- Tombol Restart -->
                    <button class="timer-btn" id="restart-btn">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                        viewBox="0 0 24 24" fill="none" stroke="currentColor" 
                        stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <polyline points="1 4 1 10 7 10" />
                        <path d="M3.51 15a9 9 0 1 0 2.13-9.36L1 10" />
                    </svg>
                    </button>
                </div>

                <div class="timer-display">
                    <span id="timer-display">25:00</span>
                </div>
            </div>
        </div>
    </section>

    <!-- Right Column -->
    <section class="content-right">
        <div class="todo-header">
            <h2>Sisa Tugas</h2>
        </div>
        <div class="todo-list" id="todo-list"></div>
    </section>
@endsection

@push('scripts')
    <script src="{{ secure_asset('js/components/categoryCard.js') }}"></script>
    <script src="{{ secure_asset('js/homePage.js') }}"></script>
@endpush

